language: cpp
sudo: required
compiler: gcc
env: QT_BASE="59"
cache: bundler
group: deprecated-2017Q4
before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt594-trusty -y;
    - sudo apt-get update -qq;
install:
    - sudo apt-get install -qq qt59-meta-minimal; source /opt/qt59/bin/qt59-env.sh;

script:
    - qmake
    - make
notifications:
    email: false
